# Generated by Django 5.2.4 on 2025-07-30 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_goal_workoutlog_workoutschedule_delete_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('requirement_type', models.CharField(choices=[('streak', 'Workout Streak'), ('total_workouts', 'Total Workouts'), ('total_minutes', 'Total Minutes'), ('calories_burned', 'Calories Burned')], max_length=50)),
                ('requirement_value', models.IntegerField()),
                ('date_earned', models.DateField(blank=True, null=True)),
                ('is_earned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BodyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(decimal_places=2, help_text='In kg', max_digits=5)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, help_text='In kg', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Core', 'Core'), ('Cardio', 'Cardio'), ('Full Body', 'Full Body')], max_length=50)),
                ('description', models.TextField()),
                ('calories_per_minute', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='Workout Session', max_length=100)),
                ('total_duration', models.PositiveIntegerField(default=0)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='exercise_category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
