# Generated by Django 5.2.4 on 2025-07-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_achievement_bodymetrics_exercise_workoutsession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='exercise_category',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Core', 'Core'), ('Cardio', 'Cardio'), ('Full Body', 'Full Body')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
